services:
  postgres:
    image: postgres:15
    container_name: eventmanager_db
    restart: always
    environment:
      POSTGRES_DB: eventmanager
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: