spring:
  application:
    name: eventmanager

  r2dbc:
    url: r2dbc:h2:mem:///eventdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:

  sql:
    init:
      mode: always
      platform: h2
      schema-locations: classpath:schema.sql
      data-locations: classpath:data.sql

jwt:
  secret: YvF7p2Xk49ZdQ83nWmLuR5vM0sHjL1aZ
  expiration: 3600000

logging:
  level:
    org.springframework.r2dbc.core: DEBUG
