spring:
  application:
    name: eventmanager

  r2dbc:
    url: r2dbc:postgresql://localhost:5432/eventmanager
    username: postgres
    password: postgres

  sql:
    init:
      mode: always

jwt:
  secret: YvF7p2Xk49ZdQ83nWmLuR5vM0sHjL1aZ
  expiration: 3600000

logging:
  level:
    org.springframework.r2dbc.core: DEBUG
